name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: "✨ Chores"
    labels:
      - "renovate"
template: |
  ## What’s Changed

  $CHANGES

  ## Contributors
  $CONTRIBUTORS
