name: Unlock SST

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to unlock (staging/production)"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  unlock-sst:
    name: Unlock SST Stage
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.stage == 'production' && 'prod' || 'dev' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Unlock SST
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
        run: npx sst unlock --stage ${{ inputs.stage }}
