import { generateCSVObject } from "../../../src/players/export";
import { PlayerCardDataType } from "../../../src/coh3/coh3-types";

describe("generateCSVObject", () => {
  const playerInfo: PlayerCardDataType = {
    steamData: {
      steamid: "123456",
      profileurl: "https://steamcommunity.com/profiles/123456",
      avatarmedium:
        "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/12/123456.jpg",
    },
    COH3PlayTime: null,
    standings: {
      german: {
        "1v1": {
          statgroup_id: 1,
          leaderboard_id: 1,
          wins: 10,
          losses: 5,
          streak: 3,
          disputes: 0,
          drops: 2,
          rank: 1,
          ranktotal: 100,
          regionrank: 1,
          ranklevel: 10,
          rating: 1000,
          regionranktotal: 1000,
          lastmatchdate: 1645430400,
        },
        "2v2": null,
        "3v3": null,
        "4v4": null,
      },
      american: {
        "1v1": null,
        "2v2": {
          statgroup_id: 2,
          leaderboard_id: 2,
          wins: 5,
          losses: 3,
          streak: 1,
          disputes: 0,
          drops: 1,
          rank: 2,
          ranktotal: 200,
          regionrank: 2,
          ranklevel: 8,
          rating: 950,
          regionranktotal: 800,
          lastmatchdate: 1645430400,
        },
        "3v3": null,
        "4v4": null,
      },
      dak: {
        "1v1": null,
        "2v2": null,
        "3v3": null,
        "4v4": null,
      },
      british: {
        "1v1": null,
        "2v2": null,
        "3v3": null,
        "4v4": null,
      },
    },
    info: { country: "USA", level: 20, name: "Player One", xp: 5000 },
  };

  test("Generates a CSV object with correct keys and values", () => {
    const csvObject = generateCSVObject(playerInfo, "abcdef", ["1v1", "2v2", "3v3", "4v4"]);

    expect(csvObject).toEqual({
      alias: "Player One",
      relic_id: "abcdef",
      steam_id: "123456",
      "1v1_axis_elo": 1000,
      "1v1_allies_elo": 0,
      "2v2_axis_elo": 0,
      "2v2_allies_elo": 950,
      "3v3_axis_elo": 0,
      "3v3_allies_elo": 0,
      "4v4_axis_elo": 0,
      "4v4_allies_elo": 0,
      german_1v1_rank: 1,
      german_1v1_elo: 1000,
      german_1v1_total: 15,
      german_2v2_rank: null,
      german_2v2_elo: null,
      german_2v2_total: null,
      german_3v3_rank: null,
      german_3v3_elo: null,
      german_3v3_total: null,
      german_4v4_rank: null,
      german_4v4_elo: null,
      german_4v4_total: null,
      american_1v1_rank: null,
      american_1v1_elo: null,
      american_1v1_total: null,
      american_2v2_rank: 2,
      american_2v2_elo: 950,
      american_2v2_total: 8,
      american_3v3_rank: null,
      american_3v3_elo: null,
      american_3v3_total: null,
      american_4v4_rank: null,
      american_4v4_elo: null,
      american_4v4_total: null,
      dak_1v1_rank: null,
      dak_1v1_elo: null,
      dak_1v1_total: null,
      dak_2v2_rank: null,
      dak_2v2_elo: null,
      dak_2v2_total: null,
      dak_3v3_rank: null,
      dak_3v3_elo: null,
      dak_3v3_total: null,
      dak_4v4_rank: null,
      dak_4v4_elo: null,
      dak_4v4_total: null,
      british_1v1_rank: null,
      british_1v1_elo: null,
      british_1v1_total: null,
      british_2v2_rank: null,
      british_2v2_elo: null,
      british_2v2_total: null,
      british_3v3_rank: null,
      british_3v3_elo: null,
      british_3v3_total: null,
      british_4v4_rank: null,
      british_4v4_elo: null,
      british_4v4_total: null,
    });
  });

  test("Generates a CSV object with different types", () => {
    const csvObject = generateCSVObject(playerInfo, "abcdef", ["1v1"]);

    expect(csvObject).toEqual({
      alias: "Player One",
      relic_id: "abcdef",
      steam_id: "123456",
      "1v1_axis_elo": 1000,
      "1v1_allies_elo": 0,
      german_1v1_rank: 1,
      german_1v1_elo: 1000,
      german_1v1_total: 15,
      american_1v1_rank: null,
      american_1v1_elo: null,
      american_1v1_total: null,
      dak_1v1_rank: null,
      dak_1v1_elo: null,
      dak_1v1_total: null,
      british_1v1_rank: null,
      british_1v1_elo: null,
      british_1v1_total: null,
    });
  });
});
