name: Generate Sitemap

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "config.ts"

jobs:
  generate-sitemap:
    name: Generate Site Map and Search Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-v2
        with:
          path: |
            node_modules
          key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install
        run: yarn --prefer-offline --frozen-lockfile install

      - name: Build
        run: yarn build

      - name: Generate Sitemap
        run: yarn sitemap

      - name: Generate Search Data
        run: yarn search-data

      - name: Prettier the stuff
        run: yarn fix

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email ""

      - name: Create New Branch
        run: |
          git checkout -b automated-content-update
          git add -A
          git commit -m "Update sitemap and search data"
          git push origin HEAD --force

      - name: Create or Update Pull Request
        run: |
          gh auth setup-git
          gh_pr_up() {
            PR_EXISTS=$(gh pr list --head automated-content-update | wc -l)
            if [ "$PR_EXISTS" -eq "0" ]; then
              gh pr create "$@"
            else
              gh pr edit "$@"
            fi
          }
          gh_pr_up --title "Update Sitemap and Search Data" --body "Automatically generated sitemap and search data update" --base master --label "bot" --head automated-content-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
